name: openwatcherhub
services:
  copernicus-s3-cache:
    build: ./copernicus-dataspace-s3-cache/
    env_file: prod.env
    restart: "always"
    volumes:
      - cache:/var/cache/nginx
  api:
    build: ./openwatcherhub-api/
    environment:
      S3_PROXY_URL: http://copernicus-s3-cache
    ports:
      - "8081:80"
    restart: "always"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  cache:
